### ISSUE TITLE
adding inputs

### ISSUE THREAD

**Issue by Hochiss** [solowalker27/homebridge-onkyo#5]
@solowalker27, I think it is better to follow-up [the discussion](https://github.com/ToddGreenfield/homebridge-onkyo/issues/33#issuecomment-520878598) here.
- Your git cannot be found at ui-x under onkyo, so I installed manually:
sudo npm install -g https://github.com/solowalker27/homebridge-onkyo.git
but ui-x still shows coming from \@todd  with the version of v0.7.1
- Your platform w. your sample config is working(e.g. on/off) with high potentials;
- Still inputs still not working for my [TX-NR636](https://www.intl.onkyo.com/downloads/manuals/pdf/tx-nr636_manual_e.pdf), I tried "dvr" or "CBL/SAT" etc, not showup;
- "volume_dimmer" is working as loudness, but HomeKit shows as "brightness"; 

In general,  where to find the KEYS/switches/commands/ etc.  it seems "node 3.js" only output generic names...  right?

![Screen Shot 2019-08-13 at 17 50 13](https://user-images.githubusercontent.com/36304198/62957381-f4e79b80-bdf4-11e9-8131-5e2f4fb16cf3.png)

**Comment by solowalker27** [comment]
I haven't published mine to npm so ui-x wouldn't be able to find it. If it's still showing Todd's it's because you haven't uninstalled Todd's. You likely could have them both installed and working at the same time due to how I have mine structured. If you don't want Todd's anymore, you can uninstall it.

The volume dimmer is supposed to appear as a light with brightness, yes. There's currently no better control to have that kind of functionality in the UI for a TV, as far as I know. On an iPhone, you can use the Remote functionality to change the volume with your hardware volume up and down buttons. I believe I'm still exposing the volume as a slider that you can find in Eve and other third-party HomeKit apps.

For inputs, I'd first try putting in your model number and then not defining any of the inputs in the config. That should default to showing you all the inputs that that model supports, if your model is specifically supported. Looking at the `eiscp` code, it should be supported. It's been a while since I've done it, but `node 3.js` int the `eiscp/examples/` directory should show you a list, I think. If not, I may be able to check for you later.

Each input needs to be named exactly how the receiver wants it or they won't work. You'd give it the names you want it to show in HomeKit in the config.

**Comment by Hochiss** [comment]
@solowalker27 please merge or start a new name? get it fly :-)

Finally I succeeded adding inputs:-) , exactly as your sample... 2 points I learnt to share here for anyone interested:
- Even though my AVR input name is STB/DVR,  the name for Homebridge input is video1; and CBL/SAT is video2; Hereby "_node 3.js_" only gives generic names, not model specific input names. In fact, an easy way to get the input name is, to use original remote and while change inputs, check log in ui-x, it will show something like:
`[Onkyo] eventInput - message: video2,cbl,sat - new i_state: 16 - input: video2`
thus **video2** is the authentic name for cbl/sat;

    In this way, all the inputs can be determined :-) 
- After change in config.json, it could be iPhone HomeKit still not show up, a new start of iPhone would be needed (don't know the reason, maybe clear cache?)

--- 
 
Next stage, would be how to navigate within the interface, that's really another big jump, because potentially it could replace any remote control for any device :-) 

and it is possible(already listed to use like apple TV remote):
![IMG_E856BA1B837F-1](https://user-images.githubusercontent.com/36304198/63110105-fba81700-bf8a-11e9-8699-0ef11c8ad427.jpeg)

![IMG_9B695256FEE9-1](https://user-images.githubusercontent.com/36304198/63111268-9b66a480-bf8d-11e9-8402-cf0bbd17d106.jpeg) ![IMG_4808](https://user-images.githubusercontent.com/36304198/63111273-9d306800-bf8d-11e9-965a-0df5347237f4.PNG)

**Comment by solowalker27** [comment]
I believe you can navigate the interface. The `i` button I think brings up the menu. You can tap the arrows for directions to move the cursor and tap the middle to select. `Back` goes back, obviously, and I think the `i` button again dismisses the menu faster than tapping `Back` repeatedly.

As far as the reboot goes, that's not likely anything I can do about it. Stuff like that happens with the HomeKit app and accessories or bridges when they change in certain conditions. That can happen with homebridge. One possibility is that you may have multiple "TVs" in homebridge. There's a known limitation in Apple's implementation of TVs so that only one TV with a Remote behind a bridge is exposed at a time. I've had to split my homebridge to multiple instances in order to get all my remotes to show up at once. Here's a link to the homebridge issue discussing it.

https://github.com/nfarina/homebridge/issues/2184#issue-424630494

**Comment by Hochiss** [comment]
Yes! I confirm the remote for Onkyo works :-) thanks!
